
Vagrant.configure("2") do |config|
  config.vm.box = "almalinux/8"
  config.vm.hostname = "app01"
  config.vm.network "private_network", ip: "192.168.1.3"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.synced_folder ".", "/vagrant", disabled: true
end
